spring: 
 application:
  name: spring-cloud-gateway
 cloud:
  gateway:
   routes:
    - id: path_route1
      uri: http://127.0.0.1:8090/servicex/name
      predicates:
      - Path=/servicex/name
    - id: path_route2
      uri: http://127.0.0.1:8090/servicex/name/dependentServices
      predicates:
      - Path=/servicex/name/dependentServices

server:
 port: 9010
 shutdown: graceful

 
